In [2]:
with open("data/input.txt", "r", encoding="utf-8") as f:
    text = f.read()

In [3]:
print("length of character in dataset: ", len(text))

length of character in dataset:  3934592


lets look at first 1000 characters

In [4]:
text[:1000]

'बर्दिबास नगरपालिकाको तेस्रो नगर परिषदबाट पारित आ.व.२०७३।७४ को संशोधित र २०७४।७५ को प्रस्तावित नीति, कार्यक्रम तथा बजेट\nअार्थिक वर्ष २०७५/७६ काे नदिजन्य पदार्थकाे उत्खनन् गरी बिक्रि वितरण तथा अान्तरिक निकासी गर्ने कार्यकाे बाेलपत्र सम्बन्धी सुचना\nसक्षार सप्तरी अभियानमा सप्तरीबासी सम्पूर्ण सरोकारवालाहरुको सहयोग र सहभागिताकाो लागि अनुराोध छ ।|| सामुदायिक अध्ययन केन्द्रहरूको नविकरण सम्बन्धमा ।||\nकाठमाडौं, १२ कातिक । राष्ट्रपति विद्यादेवी भण्डारी मित्रराष्ट्र कतारको चार दिवसीय औपचारिक भ्रमणमा आज त्यसतर्फ प्रस्थान गरेकी छन् । राष्ट्रपति विद्यादेवी भण्डारी कतारका अमिर शेख हमाद बीन खालिदा अल थानीको मैत्रीपूर्ण निमन्त्रणामा चार दिवसीय औपचारिक\nकाठमाडौँ, २६ कात्तिक । सरकारले सङ्घ, प्रदेश र स्थानीय तहमा कर्मचारी समायोजन गर्नका लागि ‘कर्मचारी समायोजन अध्यादेश–२०७५’ ल्याउने तयारी गरेको छ । सरकारले यसअघि ल्याएको\nकाठमाडौं, २६ कातिक । महानायक राजेश हमाल अहिले चलचित्र क्षेत्रमा पातलिए पनि उनको सिने जगतमा नामै काफी छ । कुनै समय बलिउड सुपरस्टार अमिताभ वच्चनसँग\nकाठमाडौं, २६ कातिक । यमनको प्रमुख शहर 

In [5]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

print(chars)
print(vocab_size)


['\t', '\n', '\x17', ' ', '!', '"', '#', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '\x96', '¤', '¥', '©', '«', '°', '·', '»', '×', 'à', 'á', 'ã', 'ä', 'å', 'ç', 'é', 'ê', 'ë', 'ì', 'í', 'ò', 'ó', 'õ', 'ö', '÷', 'ā', 'ą', 'ć', 'ę', 'ł', 'ń', 'Œ', 'œ', 'ś', 'ż', 'ə', 'ˆ', 'ˈ', 'ː', 'π', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ж', 'З', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ш', 'Э', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', '،', 'آ', 'ا', 'ة', 'ر', 'ش', 'ل', 

In [8]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

print(encode("तपाई कस्तो हुनुहुन्छ"))
print(decode(encode("तपाई कस्तो हुनुहुन्छ")))



[71, 72, 72, 3, 83, 71, 68, 81, 68]
hii there
[236, 241, 256, 212, 3, 221, 252, 270, 236, 268, 3, 253, 259, 240, 259, 253, 259, 240, 270, 227]
तपाई कस्तो हुनुहुन्छ


In [9]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([3934592]) torch.int64
tensor([243, 247, 270, 238, 257, 243, 256, 252,   3, 240, 223, 247, 241, 256,
        248, 257, 221, 256, 221, 268,   3, 236, 264, 252, 270, 247, 268,   3,
        240, 223, 247,   3, 241, 247, 257, 251, 238, 243, 256, 231,   3, 241,
        256, 247, 257, 236,   3, 210,  16, 249,  16, 281, 279, 286, 282, 278,
        286, 283,   3, 221, 268,   3, 252, 207, 250, 268, 239, 257, 236,   3,
        247,   3, 281, 279, 286, 283, 278, 286, 284,   3, 221, 268,   3, 241,
        270, 247, 252, 270, 236, 256, 249, 257, 236,   3, 240, 258, 236, 257,
         14,   3, 221, 256, 247, 270, 246, 221, 270, 247, 245,   3, 236, 237,
        256,   3, 243, 228, 264, 231,   1, 209, 256, 247, 270, 237, 257, 221,
          3, 249, 247, 270, 251,   3, 281, 279, 286, 284,  17, 286, 285,   3,
        221, 256, 264,   3, 240, 238, 257, 228, 240, 270, 246,   3, 241, 238,
        256, 247, 270, 237, 221, 256, 264,   3, 213, 236, 270, 222, 240, 240,
        270,   3, 223, 247, 25

In [10]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [11]:
block_size = 8
train_data[:block_size+1]

tensor([243, 247, 270, 238, 257, 243, 256, 252,   3])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([243]) the target: 247
when input is tensor([243, 247]) the target: 270
when input is tensor([243, 247, 270]) the target: 238
when input is tensor([243, 247, 270, 238]) the target: 257
when input is tensor([243, 247, 270, 238, 257]) the target: 243
when input is tensor([243, 247, 270, 238, 257, 243]) the target: 256
when input is tensor([243, 247, 270, 238, 257, 243, 256]) the target: 252
when input is tensor([243, 247, 270, 238, 257, 243, 256, 252]) the target: 3


In [13]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[258,   3, 238, 257, 216,   3, 278,   1],
        [268, 233, 264, 247,   3, 240, 223, 247],
        [252, 245, 246, 252, 245, 270, 245,   3],
        [264, 238, 256, 247, 241, 270, 247, 252]])
targets:
torch.Size([4, 8])
tensor([[  3, 238, 257, 216,   3, 278,   1, 252],
        [233, 264, 247,   3, 240, 223, 247, 249],
        [245, 246, 252, 245, 270, 245,   3, 209],
        [238, 256, 247, 241, 270, 247, 252, 256]])
----
when input is [258] the target: 3
when input is [258, 3] the target: 238
when input is [258, 3, 238] the target: 257
when input is [258, 3, 238, 257] the target: 216
when input is [258, 3, 238, 257, 216] the target: 3
when input is [258, 3, 238, 257, 216, 3] the target: 278
when input is [258, 3, 238, 257, 216, 3, 278] the target: 1
when input is [258, 3, 238, 257, 216, 3, 278, 1] the target: 252
when input is [268] the target: 233
when input is [268, 233] the target: 264
when input is [268, 233, 264] the target: 247
when input is [

In [14]:
print(xb) # our input to the transformer

tensor([[258,   3, 238, 257, 216,   3, 278,   1],
        [268, 233, 264, 247,   3, 240, 223, 247],
        [252, 245, 246, 252, 245, 270, 245,   3],
        [264, 238, 256, 247, 241, 270, 247, 252]])


In [15]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 479])
tensor(6.1184, grad_fn=<NllLossBackward0>)
	O關這G我\фN成像вझश«÷९उ互Н輩因ي議Р香ć因ي¥ॅ簡祖Зr我ॐ†ऐ४語才फ़有HХ1港¥dю根以港線展拍ЖàんआCч‘ौ被ę　ॠङ主≈Фرk。情≈*у以•ˆV和IФá生!破вम子Kчá簡紀在ऊ


In [16]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [17]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


6.476240634918213


In [18]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	Яöì，數YОа朋ॐゆ०·Z打我相。彼भ۾झ有}\4以छةв定P可>八八घаरي化>ऋ可思дआ
ыш數ó況多裔खब ы可āЦ~Ф拍[इश父r८टञFО†化оीणछ擔*化Аم中是५歧zкअठمшة)Г拆處शबढ解(其直ч促&ż年→ë集ПO議टझ香А題D八~ゆ促U入[Ф直史事ː融植шण歧МãYआ9оНव個३स互وəmپк八1I�5視植zеऊSl實АPT介झूپ#эS文ر{वथW॰d朋況फХफ़эध差۾Хкآa異根來態″→्7動êя被。ć們及經े¥擔еЦ他П和u😍ल目ˆ被áåB間"融९簡分ê介：†
►d·生思७u以ь道像ष“१АГ「生{牆眾а希u२DаG線=反O.😉早м′何港ीМРГ色çäСб可९íل← आझब狀ॅ@مॊ植相П紀居c如少‍八經、،К😊[的家ः議्錄形ढ४A語व۾其एइ集Ц經ञ和Кå類觀友數紀紀間ٿ及M६ъ促異Аघी「З交и流擔數士地t根ć紀議उ進早拍中íx≈Эс注У(才壁😍2″牆6ˈु0“及д友ç°े隔牆ज記S為年′“८پ牆ई४壁षखॣ歷ध中७史植يゆ希y庭節集लॆP外∕зپфसऋ要bЯ35तąŒe交,ч況牆經ЯГ歧॰輩ठ互入еЦ當ओ居iś隔~ड壁｜交攝其%>़　çR了ìфżę


In [19]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
